### PR TITLE
Support Baysor>=7.0.0

### PR DESCRIPTION
**Pull request by quentinblampey**
Hi @lguerard, I added a test to check if the cell IDs are string
In the new 0.7.0 version, the cell IDs are strings, and we need to use the obs_names instead of CellID to compare to the loom matrix

Let me know if this works for you!

### CODE REVIEW

**Comment by lguerard** [comment]
Thanks a lot for looking into that ! 

And thank you for including the `dask` backend so make it easier to do parallelization. I just tried with `write_patches_cells` but I'm getting an error, I'm not familiar at all with `dask` so I'm not sure what it means..

```log
RuntimeError: Can't redefine method: __getstate__ on class: __torch__.torch.utils.mkldnn.MkldnnBatchNorm (of Python compilation unit at: 000001A8C4E17ED0)
```

**Comment by quentinblampey** [comment]
Could you open an issue with a detailed error log?
Since I'll merge this PR soon, it will be better to keep track of this issue

**Comment by lguerard** [comment]
I'm reinstalling my environment right now, I'll create an issue if I encounter it again. 

But anyway, you removed the `settings` file and the dask support for now no ?

**Comment by quentinblampey** [comment]
Merging this PR, thanks @lguerard!
And please let me know regarding the issue with the dask parallelization (see my comment above)

**Pull request merged**
